# Generated by Django 5.1 on 2024-09-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default='103E724B32', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
