# Generated by Django 5.1 on 2024-09-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.CharField(default='7DA74788AD', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
