# Generated by Django 5.1 on 2024-09-02 12:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('47e58439-fb90-4c20-8358-cec90e37b313'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
